### ISSUE TITLE
Parser timing out 

### ISSUE THREAD

**Issue by mregan** [sepiariver/cssSweet#23] opened 2017-03-27 23:50 UTC
Environment:
- MODX Revolution 2.5.5-pl 
- PHP Version 7.0.12
- Linux 4.4.0-21-generic 
- Apache 2.0
- mysql 5.7.17-0ubuntu0.16.04.1

Running cssSweet 4.0.1-rc1 the system 'hangs' with the following error message:
`PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/develope/senior/core/components/csssweet/model/csssweet/libs/scssphp/src/Parser.php on line 874`

I have four different versions of cssSweet plugins each for a different properties for template styling. The first version will sometimes update properly, the rest always 'hang'.

That line is for a preg_match in 'function match()'. The problem seems to have to do with the value for $r

In 3.0.0-beta3 the line is `$r = '/' . $regex . '/Ais';`
In 4.0.1-rc1 the line is `$r = '/' . $regex . '/' . $this->patternModifiers;`

When I put the line from 3.0.0-beta3 into 4.0.1-rc1 it seems to work. However, I haven't done a full test - so it may have introduced another problem.

**Comment by sepiariver** [comment] 2017-06-21 16:40
Thanks so much for this @mregan Sorry it's been a delayed response. I'll look into the scssphp library's repo to see if it's a known issue.

Two possible workarounds:
1. Modify the cssSweet plugin to temporarily set the timeout higher.
2. The part that seems to take the most processing is including and parsing a lot of SCSS partials and mixins etc. You could pre-process those, and include the output in a static Chunk, since a lot of those (the ones included with frameworks, anyways) might not change as often as your site-specific SCSS.

Let's keep the thread open on this. Again sorry for the delay.

**Comment by sepiariver** [comment] 2017-06-22 06:02
Note: I couldn't find any reported issues with the Parser in scssphp. That said, making the regex flags `Ais` as you've done, should be fine. Question: are your source files in something other than utf-8?

**Comment by mregan** [comment] 2017-06-22 17:35
Thanks for your response. And, thanks for SCSS - it is a great program.

All the source files are Chunks - so, yes they are UTF-8. However, there are multiple Chunks. I have  bootstrap.css as the base then load template specific css files. When I get a chance I will try putting everything into one Chunk and try pruning the bootstrap.css file.

For now, I will just keep the regex flag as Ais, as that solves the problem.

**Comment by sepiariver** [comment] 2017-09-14 04:01
Yeah I could reproduce it on a specific implementation (but not all). Anyways I put a hotfix in the next version of cssSweet. Maybe it will be addressed in scssphp as well...?

01657a774db8f4480c20d1be5ab189950b7f2dac

**Closed by sepiariver** 2017-09-14 04:01 UTC
